require: rubocop-rspec

RSpec/ContextWording:
  Enabled: false
RSpec/FilePath:
  SpecSuffixOnly: true
RSpec/InstanceVariable:
  Enabled: false
RSpec/ExampleLength:
  Max: 10
RSpec/MultipleExpectations:
  Max: 6

AllCops:
  NewCops: enable
  Exclude:
    - Rakefile
    - Gemfile
    - file-temp.gemspec
Lint/AssignmentInCondition:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/CaseIndentation:
  IndentOneStep: true
Layout/HashAlignment:
  EnforcedHashRocketStyle: 'table'
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  PreferredName: 'err'
Naming/AccessorMethodName:
  Enabled: false
Naming/FileName:
  Exclude:
    - 'lib/file-temp.rb'
